# Generated by Django 4.0.3 on 2022-04-01 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('2baf64ab-ac1e-4f95-8fa3-36f7be33668e'), editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ae080668-a0fb-44e6-9634-ba7157c4c035'), editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'account_types',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e0424cc8-fd37-48d5-b80b-34714d4a4ad6'), editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('cpr', models.CharField(max_length=10, unique=True)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e5169f79-13d2-49ed-9a07-255194a7c70c'), editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c207052d-5e96-4328-ac8e-5770c256917b'), editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='banking_system_app.customer')),
            ],
            options={
                'db_table': 'loans',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('bca225c2-0923-47e0-a5b5-dba12a434680'), editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('cpr', models.CharField(max_length=8, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b2e7cf8d-ff59-4a9c-bf45-b612a6bc86f7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='banking_system_app.account')),
            ],
            options={
                'db_table': 'bank_details',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='banking_system_app.accounttype'),
        ),
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='banking_system_app.customer'),
        ),
        migrations.CreateModel(
            name='AccountsTransaction',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='banking_system_app.account')),
                ('transaction', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='banking_system_app.transaction')),
            ],
            options={
                'db_table': 'accounts_transactions',
                'unique_together': {('account', 'transaction')},
            },
        ),
    ]
