# Generated by Django 4.0.3 on 2022-04-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinformation',
            table='user_information',
        ),
    ]
