# Generated by Django 4.0.3 on 2022-04-01 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.UUID('43b188f3-bbfc-49e5-9250-58808f7351a3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3dd15b0f-f70a-43a9-b01d-afe24786029f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d63ebef3-07b0-4b36-9099-752b6ea8d9ce'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e9d8b8fa-3386-4eb1-b313-894215814a82'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0358379d-abfb-4445-893e-30fed44ec46b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4e28a751-f1a6-4906-9893-6e4e7fe5352f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid.UUID('91ca736d-f3d1-4a9f-862a-cd3ce240966f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
