# Generated by Django 4.0.3 on 2022-03-11 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
