# Generated by Django 4.0.3 on 2022-03-11 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system_app', '0002_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=255, unique=True)),
                ('balance', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'account_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bank_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('cpr', models.CharField(max_length=8, unique=True)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('cpr', models.CharField(max_length=8, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'loans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'transactions',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='accountstransactions',
            name='account',
        ),
        migrations.DeleteModel(
            name='AccountTypes',
        ),
        migrations.DeleteModel(
            name='BankDetails',
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.DeleteModel(
            name='Loans',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
        migrations.CreateModel(
            name='AccountsTransaction',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='banking_system_app.account')),
            ],
            options={
                'db_table': 'accounts_transactions',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
        migrations.DeleteModel(
            name='AccountsTransactions',
        ),
    ]
