# Generated by Django 4.0.3 on 2022-05-12 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system_app', '0007_alter_userinformation_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_number',
        ),
    ]
