# Generated by Django 4.0.3 on 2022-05-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system_app', '0009_add_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='user_mfa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
