# Generated by Django 4.0.3 on 2022-05-19 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system_app', '0011_rename_user_mfa_userinformation_use_mfa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownBank',
            fields=[
                ('routing_nuber', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=15)),
                ('port', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'known_banks',
            },
        ),
    ]
