# Generated by Django 4.0.3 on 2022-05-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system_app', '0012_knownbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownbank',
            name='is_local',
            field=models.BooleanField(default=False),
        ),
    ]
