# Generated by Django 4.0.3 on 2022-05-20 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system_app', '0015_account_use_mfa_alter_account_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knownbank',
            old_name='routing_nuber',
            new_name='routing_number',
        ),
    ]
