# Generated by Django 4.0.3 on 2022-05-21 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banking_system_app', '0016_rename_routing_nuber_knownbank_routing_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownbank',
            name='user_id',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
