# Generated by Django 4.0.3 on 2022-05-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system_app', '0017_knownbank_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knownbank',
            old_name='user_id',
            new_name='user',
        ),
    ]
