# Generated by Django 4.0.3 on 2022-05-23 23:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system_app', '0018_rename_user_id_knownbank_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequests',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('text', models.TextField()),
                ('is_new', models.BooleanField(default=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='banking_system_app.account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='banking_system_app.account')),
            ],
            options={
                'db_table': 'transfer_requests',
            },
        ),
    ]
