# Generated by Django 4.0.3 on 2022-06-07 23:47

import banking_system_app.Utils.generators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system_app', '0020_rename_is_paid_transferrequests_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knownbank',
            name='routing_number',
            field=models.CharField(default=banking_system_app.Utils.generators.generate_routing_number, max_length=3, primary_key=True, serialize=False),
        ),
    ]
