version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${NAME}
      - POSTGRES_USER=${USER1}
      - POSTGRES_PASSWORD=${PASSWORD}
  redis:
    image: redis:alpine  
  
  web:
    build: .
    volumes:
      - .:/banking_system
    ports:
      - "8000:8000"
    environment:
      - ENGINE=${ENGINE}
      - NAME=banking_system
      - USER1=${USER1}
      - PASSWORD=${PASSWORD}
      - HOST=db
      - PORT=${PORT}
      - SECRET_KEY=${SECRET_KEY}
      - ACCOUNT_SID=${ACCOUNT_SID}
      - AUTH_TOKEN=${AUTH_TOKEN}
      - PHONE_NUMBER=${PHONE_NUMBER}
      - REDIS=redis
    depends_on:
      - db
      - redis



