# Generated by Django 4.0.3 on 2022-05-06 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='banking_system_app.account'),
        ),
    ]
