# Generated by Django 4.0.3 on 2022-05-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system_app', '0002_alter_accountstransaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
