# Generated by Django 4.0.3 on 2022-05-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system_app', '0006_alter_userinformation_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
