# Generated by Django 4.0.3 on 2022-05-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system_app', '0010_userinformation_user_mfa_alter_account_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='user_mfa',
            new_name='use_mfa',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
