# Generated by Django 4.0.3 on 2022-05-20 20:20

import banking_system_app.Utils.generators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system_app', '0014_account_routing_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='use_mfa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(default=banking_system_app.Utils.generators.generate_account_number, editable=False, max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='knownbank',
            name='routing_nuber',
            field=models.CharField(default=banking_system_app.Utils.generators.generate_routing_number, editable=False, max_length=3, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='BankDetail',
        ),
    ]
