# Generated by Django 4.0.3 on 2022-05-24 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system_app', '0019_transferrequests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferrequests',
            old_name='is_paid',
            new_name='is_closed',
        ),
    ]
